---
- hosts: devstack
  gather_facts: no
  become: true
  become_user: root
  become_method: sudo

  vars_files:
    - "vars/params.yml"

  tasks:

  - name: Download DevStack
    become_user: stack
    become_method: sudo
    become: true
    ignore_errors: yes
    shell: |
      cd ~
      git clone https://git.openstack.org/openstack-dev/devstack -b stable/{{ devstack.version }}

  - name: Create local.conf file and tranfer it to the Devstack host
    become_user: stack
    become_method: sudo
    become: true
    template:
      src: "{{ devstack.templateFile }}"
      dest: /opt/stack/devstack/local.conf

  - name: Install Devstack
    become_user: stack
    become_method: sudo
    become: true
    command: /opt/stack/devstack/stack.sh
    register: devstackresult

  - name: show output
    debug:
      var: devstackresult.stdout
