---
- hosts: devstack
  gather_facts: no
  become: true
  become_user: root
  become_method: sudo

  vars_files:
    - "vars/params.yml"

  tasks:

  - name: Update repositories cache and install the list of packages
    become: true
    apt:
      name: "{{ item }}"
      update_cache: yes
    loop: "{{ PackageList }}"


  - name: Upgrade all packages to the latest version
    become: true
    apt:
      force_apt_get: True
      name: "*"
      force_apt_get: True
      state: latest

  - name: Add the user 'stack'
    become: true
    user:
      name: "{{ devstack.user }}"
      shell: /bin/bash
      home: /opt/stack

  - name: Update sudoers group
    become: true
    lineinfile:
      dest: /etc/sudoers
      line: "stack ALL=(ALL) NOPASSWD: ALL"
