- name : configure openstack
  hosts: localhost
  connection: local
  gather_facts: no


  vars_files:
    - "vars/params.yml"

  vars:
    OpenStackEnvProvider:
      OS_AUTH_URL: http://{{ devstack.ip }}/identity
      OS_PASSWORD: "{{ devstack.password }}"
      OS_AUTH_TYPE: password
      OS_IDENTITY_API_VERSION: 3
      OS_PROJECT_DOMAIN_ID: default
      OS_USER_DOMAIN_ID: default
      OS_PROJECT_NAME: "{{ openstack.projectProvider }}"
      OS_USERNAME: "{{ openstack.username }}"
      OS_TENANT_NAME:  "{{ openstack.projectProvider }}"

    OpenStackEnvTenant:
      OS_AUTH_URL: http://{{ devstack.ip }}/identity
      OS_PASSWORD: "{{ devstack.password }}"
      OS_AUTH_TYPE: password
      OS_IDENTITY_API_VERSION: 3
      OS_PROJECT_DOMAIN_ID: default
      OS_USER_DOMAIN_ID: default
      OS_PROJECT_NAME: "{{ openstack.projectTenant }}"
      OS_USERNAME: "{{ openstack.username }}"
      OS_TENANT_NAME:  "{{ openstack.projectTenant }}"

  tasks:

    - name:
      debug:
        msg:
          - "{{ item.0.name }}"
          - "{{ item.1.protocol }}"
#      loop: "{{ openstack.securityGroups }}"

      with_subelements:
        - "{{ openstack.securityGroups }}"
        - rules
