- name : configure openstack network
  hosts: localhost
  connection: local
  gather_facts: no


  vars_files:
    - "vars/params.yml"

  vars:
    OpenStackEnvProvider:
      OS_AUTH_URL: http://{{ devstack.ip }}/identity
      OS_PASSWORD: "{{ devstack.password }}"
      OS_AUTH_TYPE: password
      OS_IDENTITY_API_VERSION: 3
      OS_PROJECT_DOMAIN_ID: default
      OS_USER_DOMAIN_ID: default
      OS_PROJECT_NAME: "{{ openstack.projectProvider }}"
      OS_USERNAME: "{{ openstack.username }}"
      OS_TENANT_NAME:  "{{ openstack.projectProvider }}"

    OpenStackEnvTenant:
      OS_AUTH_URL: http://{{ devstack.ip }}/identity
      OS_PASSWORD: "{{ devstack.password }}"
      OS_AUTH_TYPE: password
      OS_IDENTITY_API_VERSION: 3
      OS_PROJECT_DOMAIN_ID: default
      OS_USER_DOMAIN_ID: default
      OS_PROJECT_NAME: "{{ openstack.projectTenant }}"
      OS_USERNAME: "{{ openstack.username }}"
      OS_TENANT_NAME:  "{{ openstack.projectTenant }}"

  tasks:

    - name: Uploading a glance image
      os_image:
        name: "{{ item.name }}"
        container_format: bare
        disk_format: qcow2
        state: present
        filename: "{{ item.fileName }}"
      environment: "{{ OpenStackEnvProvider }}"
      loop: "{{ openstack.glance }}"
