---
PackageList:
  - libvirt-bin
  - git

devstack:
  user: stack
  version: queens
  ip: 192.168.139.136
  password: avi123
  net: 192.168.139.0/24
  gw: 192.168.139.2
  if: ens32
  dhcpStart: 192.168.139.100
  dhcpEnd: 192.168.139.120
  privateNet: 10.0.0.0/22
  templateFile: local.conf.j2

openstack:
  username: admin

  project:
    provider: admin
    tenant: demo

  externalNetwork: public

  network:
    provider:
      - name: net-avi
        subnet: subnet-avi
        cidr: 192.168.1.0/24
        external: false
        shared: false
      - name: net-infra
        subnet: subnet-infra
        cidr: 192.168.2.0/24
        external: false
        shared: true
    tenant:
      - name: net-client
        subnet: subnet-client
        cidr: 10.1.7.0/24
        dns_nameservers:
          - 192.168.2.50
      - name: net-server
        subnet: subnet-server
        cidr: 172.16.3.0/24
        dns_nameservers:
          - 172.16.3.1

  router:
    provider:
      - name: router-admin
        network: public
        interfaces:
          - net: net-avi
            subnet: subnet-avi
    tenant:
      - name: router-demo
        network: public
        interfaces:
          - net: net-client
            subnet: subnet-client
          - net: net-server
            subnet: subnet-server
          - net: net-infra
            subnet: subnet-infra

  glance:
    - name: Ubuntu-Xenial-Server
      fileName: /home/avi/bin/ubuntu/xenial-server-cloudimg-i386-disk1.img

  key:
    - name: keyPairs1
      public_key_file: /home/avi/.ssh/id_rsa.azure.pub

  securityGroups:
    - name: sg-allow-all
      description: 'security group Allow All'
      rules:
        - direction: ingress
          protocol: icmp
          port_range_min: -1
          port_range_max: -1
          remote_ip_prefix: 0.0.0.0/0
        - direction: ingress
          protocol: tcp
          port_range_min: 1
          port_range_max: 65535
          remote_ip_prefix: 0.0.0.0/0
        - direction: ingress
          protocol: udp
          port_range_min: 1
          port_range_max: 65535
          remote_ip_prefix: 0.0.0.0/0

  vm:
    # defaultImage: cirros-0.3.5-x86_64-disk
    # defaultFlavor: cirros256
    defaultSecurityGroups: sg-allow-all
    defaultImage: Ubuntu-Xenial-Server
    defaultFlavor: ds1G
    defaultKey: keyPairs1
    defaultServerUserData: |
      #!/bin/bash
      MYIP=$(ifconfig ens3|grep 'inet addr'|awk -F: '{print $2}'| awk '{print $1}')
      while true; do echo -e "HTTP/1.0 200 OK\r\n\r\nWelcome to $MYIP!" | sudo nc -l -p 80 ; done&
    network:
      server: net-server
      client: net-client
    servers:
      - name: server1
      - name: server2
    clients:
      - name: client1

vmServer:
  templateFile: server.j2
  output:
    - /home/avi/aviOs/vars/server.yml
